package javaLabProjeOdev.business.grade;

import java.util.ArrayList;
import java.util.List;

import javaLabProjeOdev.entities.grade.Grade;

public class GradeManager {
	
	// Grade list which is automatically generated by setGrade method
	List<Grade> grades = new ArrayList<Grade>();

	public GradeManager() {
		
	}
	
	// Setting grade for student with important details.
	public boolean setGrade(Grade grade) {
		
		if(grade.getCourseName() != "" && grade.getName() != "" && grade.getSurname() != "" && grade.getCourseCode() != "" && grade.getLecturerName() != "" && grade.getLecturerSurname() != "" && grade.getGrade() != "") {
			grade.setGrade("75");
			grades.add(grade);
			return true;
		}
		return false;
	}
	
	// Showing grades list
	public List<Grade> showGrades(){
		return grades;
	}
}
